//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeyadLeyaad1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity;
    using System.Globalization;
    using System.Web.Security;
    
    public partial class Contribution
    {

        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id_Contribution { get; set; }
        public int Id_Donor { get; set; }
        public string Category { get; set; }
        public string Sub_Category { get; set; }
        public string Position { get; set; }
        public string Description { get; set; }
        public System.DateTime Modified_Status_Date { get; set; }
        public string Status { get; set; }
        public Nullable<int> years { get; set; }
    }
}
