//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeyadLeyaad1.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity;
    using System.Globalization;
    using System.Web.Security;


    public partial class Donor
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id_Donor { get; set; }
        [Required]
        public string First_Name { get; set; }
        [Required]
        public string Last_Name { get; set; }
        [Required]
        public string City { get; set; }
        [Required]
        public string Street { get; set; }
        [Required]
        public int Building { get; set; }
        [Required]
        public int House { get; set; }
        [Required]
        public int Floor { get; set; }
        [Required]
        public string Phone { get; set; }
        public string Another_Phone { get; set; }
        public string Email { get; set; }
        public string Fax { get; set; }
        public string Comments { get; set; }
    }
}
