//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeyadLeyaad1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donor
    {
        public int Id_Donor { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string City { get; set; }
        public string Street { get; set; }
        public int Building { get; set; }
        public int House { get; set; }
        public int Floor { get; set; }
        public string Phone { get; set; }
        public string Another_Phone { get; set; }
        public string Email { get; set; }
        public string Fax { get; set; }
        public string Comments { get; set; }
    }
}
