//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeyadLeyaad1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public string Day { get; set; }
        public string Start_Time { get; set; }
        public string End_Time { get; set; }
        public int Id_User { get; set; }
        public bool User_Type { get; set; }
    }
}
